### ISSUE TITLE
issues setting up symportal on Mac

### ISSUE THREAD

**Issue by cdesouza02** [reefgenomics/SymPortal_framework#134]
Hello,

I am trying to set up Symportal on my Mac using the instructions on GitHub and am running into some issues on step 4. creating the database

After I run 
$ python3 manage.py migrate

I get this result:
 Operations to perform:
  Apply all migrations: dbApp
Running migrations:
  No migrations to apply.

I have downloaded the latest version of python, and it still gives me the same error. I have also tried to set up symportal on unity and still run into issues with this step.

Is there a known solution here? 

best,

caroline

**Comment by reefgenomics** [comment]
Hello, we are no longer supporting the local installation as we have to prioritize/focus. I hope you understand. Symportal.org provides automated analysis. Thank you, Chris
