### ISSUE TITLE
issues setting up symportal on Unity

### ISSUE THREAD

**Issue by cdesouza02** [reefgenomics/SymPortal_framework#135]
Hello,

I also tried to set up Symportal on Unity and also had errors on step 4.

However the error was in activating the environment.

This is the error message :
CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
you might need to `module load miniconda`.

I tried editing the shell and adding a conda initialization script, but that led to the same error message.

**Comment by reefgenomics** [comment]
Hello, we are no longer supporting the local installation as we have to prioritize/focus. I hope you understand. Symportal.org provides automated analysis. Thank you, Chris
